- include/coin/config_coinutils_default.h
This patch allows coin to use built-in type for 64-bit integer provided by Microsoft Compiler. The original code includes directly the file **BaseTsd.h** which should not be included outside **Windows.h**.
For this reason, it prevents to compilation if **_WIN32_WINNT** is >= 0x0600 because of this part of code:
```c++
#if _WIN32_WINNT >= 0x0600 || (defined(__cplusplus) && defined(WINDOWS_ENABLE_CPLUSPLUS))
//...
#define MAXUINT     ((UINT)~((UINT)0))
#define MAXINT      ((INT)(MAXUINT >> 1))
//...
#endif
```
Both **UINT** and **INT** are not defined in this header.
> Use built-in type for 64-bit integer type provided by Microsoft compiler for coin

- include/ogdf/internal/decomposition/TricComp.h
For unknown reason, some interface related information we’re put in cpp
code instead of h file; They also hadn’t followed doxygen conventions.
> Improve docs in TricComp

- src/ogdf/energybased/FMMMLayout.cpp
- src/ogdf/energybased/fmmm/Multilevel.cpp
- src/ogdf/energybased/fmmm/Set.cpp
FMMMLayout should produce same result for same random seed, but, it doesn't.
I've fixed it.
test code
```c++
#include <ogdf/basic/Graph.h>
#include <ogdf/basic/graph_generators.h>
#include <ogdf/energybased/FMMMLayout.h>
using namespace ogdf;
int main()
{
Graph G;
randomSimpleGraph(G, 10, 20);
for (int i = 0; i < 10; ++i) {
GraphAttributes GA(G, GraphAttributes::nodeGraphics |
GraphAttributes::edgeGraphics |
GraphAttributes::nodeLabel |
GraphAttributes::nodeStyle |
GraphAttributes::edgeType |
GraphAttributes::edgeArrow |
GraphAttributes::edgeStyle);
FMMMLayout layout;
layout.randSeed(42);
layout.initialPlacementForces(FMMMOptions::InitialPlacementForces::RandomRandIterNr);
layout.call(GA);
auto v = G.firstNode();
std::cout << GA.x(v) << ", " << GA.y(v) << std::endl;
}
return 0;
}
``` …
> Fix setting random seed for FMMMLayout

- src/ogdf/basic/System.cpp
Compiling with MingW (5.3.0) caused an error by duplicate macro definition of **__cpuid** (included from **intrin.h** and **cpuid.h**)
*src\ogdf\basic\System.cpp:77:27: error: macro "__cpuid" requires 5 arguments, but only 2 given*
> Fix for compilation with MingW32

- src/ogdf/fileformats/DotParser.cpp
- test/resources/fileformats/dot/valid/cluster
- test/src/basic/fileformats.cpp
This change should fix the first part of https://github.com/ogdf/ogdf/issues/36. Previously, we were reassigning the node to a cluster with less depth, contrary to the comment.
> fix DOT parser cluster depth bug

- src/coin/CoinUtils/CoinOslFactorization2.cpp
This PR adds a very minor fix for builds that have the symbol `DEBUG` defined. This commonly happens on MSVC, where many libraries may use this flag to enable extra debugging code.
With `DEBUG` defined, the file `src/coin/CoinUtils/CoinOslFactorization2.cpp` does not compile due to `int i` being duplicate in the same scope.
> src/coin/CoinUtils/CoinOslFactorization2.cpp: Minor fix for debug build

- cmake/compiler-specifics.cmake
- cmake/ogdf.cmake
Newer versions of Visual Studio ship the ClangCL compiler front-end. ClangCl can have a significant impact on the efficiency of the compiled code, with typical speedups anywhere between 5% and 30%.
This PR allows OGDF to be compiled with ClangCl. The changes are rather minor. The change in `cmake/compiler-specifics.cmake` is not a strict requirement, but it allows to correctly set warnings for MSVC with ClangCL by moving the MSVC settings above the plain Clang settings.
> Minor fixes for MSVC ClangCl build

- src/ogdf/fileformats/DotLexer.cpp
Sorry for my bad english((
Imagine we have string like
```
digraph G { node [fontsize=12] .....
```
After tokenizing numeric literal 12 the lexer sets the current char pointer/index to right bracket character. But because this process is inside the loop, the pointer is incremented again and erroneously skips the right bracket.
> Fixed numeric literal tokenization in DotLexer.cpp

- src/ogdf/energybased/FMMMLayout.cpp
- test/src/layout/energy-based.cpp
When using high level options with the FMMMLayout, low level parameters
related to page format, new initial placement and quality vs speed will
be automatically set.
Nervertheless as a side effect some not concerned parameters that might
have been overridden using the dedicated setter methods in the layout
class are resetted to their default value.
For instance, if one sets the AllowedPositions parameter to All while
using high level options, its value will be reset to Integer at the
beginning of the layout process leading to unexpected result.
Parameters are already set to their default value in the FMMMLayout
constructor so there is no need to reset them when setting low level
parameters from high level options.
The issue has been observed by a Tulip user tweaking layout parameters
from …
> FMMMLayout: Prevent parameters overriding when using high level options

- src/ogdf/basic/System.cpp
As seen here: https://docs.microsoft.com/en-us/cpp/intrinsics/cpuid-cpuidex `__cpuid` is only supported on x86 and x64.
With this change I am able to build and successfully run the tests natively on ARM64 windows. Screenshot showing test results from a ARM64 Windows VM running on my M1 macbook.
Please don't hesitate to ask for further info or changes. Thanks 👍
> Support ARM64 windows

- .github/workflows/check-build-test.yml
- cmake/compiler-specifics.cmake
- cmake/ogdf.cmake
This assigns proper names to the individual job steps, allowing them to be properly set as required for merging PRs.
I could no longer reproduce the Windows problems from #97. 
`ccache` is now used on all platforms (including Windows), the script in the comment below can be used to check its coverage.
Finally, the new build flag `OGDF_ARCH` can be used to control the value of `-march`, defaulting to `native`. In the case of our CI, this ensures that the cached binaries are compatible with the oldest generation of runner machines ([`haswell`](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html)), but this should also be useful for generating portable builds that can be packaged on conan, pypi, etc. (using [`x86-64`](https://stackoverflow.com/questions/27786932/what-is-the-default-for-gcc-ma …
> Fix CI ccache usage, add `OGDF_ARCH` parameter

- doc/examples/layout/hierarchical.cpp
- include/ogdf/basic/AdjEntryArray.h
- include/ogdf/basic/Array.h
- include/ogdf/basic/EdgeArray.h
- include/ogdf/basic/FaceArray.h
- include/ogdf/basic/GraphList.h
- include/ogdf/basic/Graph_d.h
- include/ogdf/basic/NodeArray.h
- include/ogdf/basic/PriorityQueue.h
- include/ogdf/basic/exceptions.h
- include/ogdf/basic/simple_graph_alg.h
- include/ogdf/cluster/ClusterArray.h
- include/ogdf/graphalg/MinSteinerTreeDirectedCut.h
- include/ogdf/hypergraph/HypergraphArray.h
- src/ogdf/basic/Graph.cpp
- src/ogdf/basic/System.cpp
- src/ogdf/basic/simple_graph_alg.cpp
- src/ogdf/cluster/ClusterPlanarity.cpp
- src/ogdf/fileformats/GraphIO.cpp
- src/ogdf/orthogonal/OrthoLayout.cpp
This PR fixes minor inconsistencies and annoyances  throughout the code base. There are two important changes:
- ogdf::Exception now derives from std::exception, so it can also be properly caught by generic exception handlers
- NodeArrays, EdgeArrays and the like no longer contain trash if no explicit default value is specified. This comes as no additional overhead as the default values is always copied anyways, but previously it might have contained trash if not explicitly specified (e.g. in case of pointers).
> Minor Improvements

- include/ogdf/basic/Logger.h
This allows setting a-per instance indent for OGDF Loggers, which is especially useful when debugging nested code. By creating an `Indent _{mylogger};` variable, the indentation can be increased by one until the end of the current scope.
> Auto-indent support for Logger

- .github/workflows/check-build-test.yml
- util/docker/Dockerfile.template
- util/docker/build.sh
- util/docker/clang/Dockerfile
- util/sonar.sh
Removing gcovr/pip from all gcc images also gets rid of potential problems with building docker images in the future.
> docker: Install tools for static analysis in clang image

- test/src/basic/fileformats.cpp
This addresses issue #210.
When compiling the library with gcc version 13 some warning are thrown. Most of those are fixed in this pr. One warning related memory management in the `minisat` library is not resolved.
> Compatibility with gcc 13

- doc/workflow.md
- util/style/test_clang_format.sh
When moving it to util/style/, some instances of its use were overlooked.
> Fix path to test_clang_format.sh

- .github/workflows/check-build-test.yml
- util/style/test_clang_format.sh
CI had issues with invalid cached binaries on mac OS, so report CPU info to allow debugging this the next time. Update Actions to use Node 20 to silence warnings. Change `test_clang_format` to prefer sudo-less `podman` on systems where this is available (or use whatever container runtime is specified via env variable).
> Minor updates to CI and scripts

- .github/workflows/check-build-test.yml
- .gitlab-ci.yml
- README.md
- doc/ogdf-footer.html
- include/ogdf/basic/ArrayBuffer.h
- include/ogdf/geometric/cr_min/geometry/objects/Polygon.h
- include/ogdf/graphalg/MatchingModule.h
- include/ogdf/graphalg/SpannerElkinNeiman.h
Next to actually enabling gcc-13-builds and some miscellaneous changes, this contains a quick fix for a stringop-overflow warning in `ArrayBuffer::compactCopy`. A more long-term fix would be to replace int by size_t as the default INDEX type for `ArrayBuffer`s, see #197.
Close #210
> Use gcc 13 in CI builds

- doc/examples/decomposition/decomposition.dox
- doc/examples/decomposition/four-block-tree.cpp
- doc/examples/examples.dox
- include/ogdf/decomposition/FourBlockTree.h
- src/ogdf/decomposition/FourBlockTree.cpp
- test/src/decomposition/four-block-tree.cpp
This is an implementation of [10.48550/arXiv.2308.16020](https://doi.org/10.48550/arXiv.2308.16020).
I've taken the code linked there and refactored it slightly to conform to OGDF's coding standards.
As far as I can tell, OGDF *usually* lets an `adjEntry` designate the face to its *right*.
Is that the convention, or is that only the case for `ConstCombinatorialEmbedding`?
If the former, I'll change it in the interface of `FourBlockTree` and `FourBlockTreeBuilder` as well.
> Add 4-block tree

- doc/ogdf-doxygen.cfg
- doc/porting/unreleased.md
- include/ogdf/basic/CombinatorialEmbedding.h
- include/ogdf/basic/DisjointSets.h
- include/ogdf/basic/Graph_d.h
- include/ogdf/basic/Observer.h
- include/ogdf/basic/PQTree.h
- include/ogdf/basic/RegisteredArray.h
- include/ogdf/basic/internal/copy_move.h
- include/ogdf/cluster/ClusterGraph.h
- include/ogdf/graphalg/MinSteinerTreeShore.h
- include/ogdf/hypergraph/Hypergraph.h
- include/ogdf/planarity/EmbedderMaxFace.h
- include/ogdf/planarity/EmbedderMinDepth.h
- include/ogdf/planarity/EmbedderMinDepthPiTa.h
- include/ogdf/simultaneous/SimDraw.h
- include/ogdf/upward/SubgraphUpwardPlanarizer.h
- src/ogdf/planarity/EmbedderMaxFace.cpp
- src/ogdf/planarity/EmbedderMaxFaceLayers.cpp
- src/ogdf/planarity/EmbedderMinDepth.cpp
- src/ogdf/planarity/EmbedderMinDepthPiTa.cpp
- src/ogdf/simultaneous/SimDraw.cpp
- src/ogdf/upward/SubgraphUpwardPlanarizer.cpp
- test/src/basic/disjointsets.cpp
- test/src/graphalg/planar-separator.cpp
This rightfully deletes the copy constructor and assignment operators of `Graph` (and actually all `Observable`s and `Observer`s), strictly requiring the use of `NodeArrayP<Graph>` instead of the somewhat broken `NodeArray<Graph>` (which only compiled because the auto-generated move support of `Graph` ignored that a lot of stuff would need updating and is otherwise broken at runtime). It also adds a useful warning to `NodeArray` towards this as well as Macros which help with declaring copy and move support for classes. Note: it seems that on MSVC Versions <17 (we use 16), classes with `NodeArrayP` members need to be explicitly (and rightfully) marked as non-copyable, all other compilers pick this up automatically.
> Mark Graph as immovable

- include/ogdf/packing/ComponentSplitterLayout.h
- src/ogdf/packing/ComponentSplitterLayout.cpp
- src/ogdf/packing/SimpleCCPacker.cpp
- test/src/layout/misc.cpp
The `ComponentSplitterLayout` and `SimpleCCPacker` layout modules in OGDF draw each connected component of a graph with a provided layout algorithm then pack the resulting drawings.
However, the drawings of components with edge bends were not taken into account in the previous implementation.
Indeed when using a layout algorithm that produces edge bends with those  layouts, those were not available in the `GraphAttributes` passed as parameter to `ComponentSplitterLayout::call` or `SimpleCCPacker::call` method.
This PR ensures edge bends are preserved after each connected component drawing but also taken into consideration when performing the packing operation.
For the record, I maintain a fork of [Tulip](https://tulip.labri.fr) for fun and non-profit, relicensed under GPL, that I named …
> Ensure edge bends are preserved when using layouts with packing operation

- .github/prune-all-caches.sh
- .github/prune-caches.sh
- .github/workflows/check-build-test.yml
- .github/workflows/prune-caches.yml
- .github/workflows/sonar.yml
- .gitignore
- include/ogdf/graphalg/Triconnectivity.h
- src/ogdf/graphalg/Triconnectivity.cpp
- test/src/decomposition/triconnectivity.cpp
- util/compile_for_tests.sh
This fixes several CI issues:
- The prune caches jobs only pruned cached of the master branch because the "workflow-finished" trigger is always running against master and it's hard to know the branch of the triggering workflow. Now we simply always deduplicate the caches of all branches.
-  The CI stopped using ccache on Linux/MacOs because the `cmakecommand` was no longer split correctly (or at all), thus cramming all args into a unused `DCGAL_DO_NOT_WARN_ABOUT_CMAKE_BUILD_TYPE` flag.
- The planaritzation test produced stack overflows on the Mac OS debug build. The culprit was the `Triconnectivity` class, where I unrolled a recursion into a loop. For doing so, I also added some initial tests that should be extended when tackling #207.
- ~Also included is a small fix for …
> CI and Triconnectivity fixes

- include/ogdf/basic/memory/PoolMemoryAllocator.h
- src/ogdf/basic/memory/PoolMemoryAllocator.cpp
Hi,
When I build my app which uses `ogdf` using Windows GCC (MINGW), I have this error:
```
ogdf/include/ogdf/basic/memory/PoolMemoryAllocator.h:79:33: error: function 'static bool ogdf::PoolMemoryAllocator::checkSize(size_t)' definition is marked dllimport
79 |         static OGDF_EXPORT bool checkSize(size_t nBytes) { return nBytes < TABLE_SIZE; }
|                                 ^~~~~~~~~
```
This PR fixed the issue by moving the function _definition_ from .h file to .cpp file.
This is a gcc only issue (on Windows, build as DLL)
> Fix buiding with windows gcc (mingw) as dll

- .github/workflows/sonar.yml
Currently all sonar runs (even those of PRs) are interpreted as if they were for master. This re-adds the missing information, but still leaves the slight inprecision of reporting the PR head sha, not the sha of GitHubs synthetic merge commit.
> fix sonar not picking up PR info

- .github/workflows/check-build-test.yml
- util/compile_for_tests.sh
- util/docker/Dockerfile
- util/docker/build-all.sh
- util/docker/build.sh
- util/docker/clang/Dockerfile
- util/test_coverage.sh
- util/test_self-sufficiency.sh
- util/test_static_analysis.sh
It seems that ccache drastically speeds up CI runs, roughly from 45min down to 5min if nothing changed. Unfortunately, GitHub won't let us store more than 10GB of caches, which is by far not enough. Additionally, this caching doesn't help much when compiling locally. Fortunately, ccache can also use an additional [remote cache](https://ccache.dev/manual/latest.html#_remote_storage_backends) via HTTP GET (and optionally, PUT).
For testing this, I created a [hetzner storage box](https://docs.hetzner.com/de/storage/storage-box/) with the required WebDAV functionality, 1TB storage and unlimited traffic for currently less 4€/month. As hetzner requires HTTPS, which ccache does not support, I added `mitmproxy` as background service that simply (un)wraps the HTTP(S) traffic for `ccache`. I added …
> ccache remote storage

- include/ogdf/cluster/MaximumCPlanarSubgraph.h
- include/ogdf/cluster/sync_plan/SyncPlan.h
- include/ogdf/graphalg/MatchingBlossomV.h
- src/ogdf/basic/graph_generators/clustering.cpp
- src/ogdf/cluster/HananiTutteCPlanarity.cpp
- test/src/graphalg/a-star-search.cpp
- util/fix_includes.sh
I am a member of Microsoft vcpkg, due to there are new changes merged by microsoft/STL#5105, which revealed a conformance issue in `ogdf`. It must add include `<chrono>` to fix this error.
Compiler error with this STL change:
```
D:\b\ogdf\src\3b65b433a9-facc12a078.clean\src\ogdf\cluster\HananiTutteCPlanarity.cpp(47): error C2039: 'high_resolution_clock': is not a member of 'std::chrono'
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\__msvc_chrono.hpp(286): note: see declaration of 'std::chrono'
D:\b\ogdf\src\3b65b433a9-facc12a078.clean\src\ogdf\cluster\HananiTutteCPlanarity.cpp(47): error C2873: 'high_resolution_clock': symbol cannot be used in a using-declaration
```
> Include `<chrono>` for high_resolution_clock

- doc/porting/unreleased.md
- include/ogdf/basic/memory/PoolMemoryAllocator.h
- src/ogdf/basic/memory/PoolMemoryAllocator.cpp
- test/src/basic/memory-allocator.cpp
When profiling the runtime of an algorithm, I often run it multiple times like so:
```cpp
for (int i = 0; i < 10; ++i) {
auto start = chrono::high_resolution_clock::now();
bool plan = isPlanar(G); // or, e.g., isTriconnected(G)
auto end = chrono::high_resolution_clock::now();
chrono::nanoseconds elapsed = end - start;
cout << i << ", " << plan << ", " << elapsed.count() << endl;
}
```
With the current OGDF compiled with memory manager `POOL_NTS`, I often saw the first of the 10 runs to be by far the fastest (especially when running the program multiple times consecutively, and independently of the algorithm used). This was very counter intuitive, as I expected the memory allocations of the first run to be an overhead, while later runs should be faster through reusing this memory from the …
> Fix PoolMemoryAllocator Issues

- include/ogdf/basic/simple_graph_alg.h
- include/ogdf/tree/TreeLayout.h
- src/ogdf/tree/TreeLayout.cpp
It's broken and can be simulated with `G.reverseAllEdges()`, so rather than implementing it, we just remove it.
Close #195
> Remove TreeLayout::RootSelectionType::Sink
